#!/usr/bin/env python3
"""
Agent Index Updater Hook
Auto-updates AGENT-INDEX.yaml when agents are created/modified.

Hook Events: PostToolUse (Write/Edit to agents/)
Version: 1.0.0
"""

import sys
import json
from pathlib import Path
from datetime import datetime

BASE_DIR = Path(__file__).parent.parent.parent
AGENTS_DIR = BASE_DIR / "agents"
AGENT_INDEX = AGENTS_DIR / "AGENT-INDEX.yaml"
UPDATE_LOG = BASE_DIR / "logs" / "agent-index-updates.jsonl"

# Layer paths
LAYER_PATHS = {
    "L0": "core/jarvis/",
    "L1": "agents/conclave/",
    "L2": "agents/boardroom/",
    "L3": "agents/minds/",
    "L4": "agents/cargo/",
    "SUB": ".claude/jarvis/sub-agents/"
}


def parse_stdin():
    """Parse JSON from stdin."""
    try:
        return json.load(sys.stdin)
    except Exception:
        return {}


def is_agent_file(file_path: str) -> bool:
    """Check if file is an agent definition."""
    path = Path(file_path)
    return (
        'agents/' in file_path and
        path.name in ['AGENT.md', 'SOUL.md', 'MEMORY.md'] and
        '_templates' not in file_path
    )


def detect_layer(file_path: str) -> str:
    """Detect which layer the agent belongs to."""
    if 'conclave/' in file_path:
        return 'L1'
    elif 'boardroom/' in file_path:
        return 'L2'
    elif 'minds/' in file_path:
        return 'L3'
    elif 'cargo/' in file_path:
        return 'L4'
    elif 'sub-agents/' in file_path:
        return 'SUB'
    elif 'jarvis/' in file_path:
        return 'L0'
    return 'UNKNOWN'


def extract_agent_id(file_path: str) -> str:
    """Extract agent ID from path."""
    path = Path(file_path)
    # Go up from AGENT.md to get the agent folder name
    return path.parent.name


def scan_agents() -> dict:
    """Scan all agents and build index."""
    agents = {
        'minds': [],
        'cargo': {'sales': [], 'marketing': [], 'operations': [], 'c-level': [], 'other': []},
        'conclave': [],
        'autonomous': [],
        'sub_agents': []
    }

    # Scan minds
    minds_dir = AGENTS_DIR / "minds"
    if minds_dir.exists():
        for agent_dir in minds_dir.iterdir():
            if agent_dir.is_dir() and not agent_dir.name.startswith('_'):
                agent_file = agent_dir / "AGENT.md"
                if agent_file.exists():
                    agents['minds'].append({
                        'id': agent_dir.name,
                        'path': str(agent_dir.relative_to(BASE_DIR)),
                        'has_soul': (agent_dir / "SOUL.md").exists(),
                        'has_memory': (agent_dir / "MEMORY.md").exists()
                    })

    # Scan conclave
    conclave_dir = AGENTS_DIR / "conclave"
    if conclave_dir.exists():
        for agent_dir in conclave_dir.iterdir():
            if agent_dir.is_dir():
                agent_file = agent_dir / "AGENT.md"
                if agent_file.exists():
                    agents['conclave'].append({
                        'id': agent_dir.name,
                        'path': str(agent_dir.relative_to(BASE_DIR))
                    })

    # Scan cargo (grouped)
    cargo_dir = AGENTS_DIR / "cargo"
    if cargo_dir.exists():
        for group_dir in cargo_dir.iterdir():
            if group_dir.is_dir():
                group_name = group_dir.name
                if group_name not in agents['cargo']:
                    agents['cargo'][group_name] = []
                for agent_dir in group_dir.iterdir():
                    if agent_dir.is_dir():
                        agent_file = agent_dir / "AGENT.md"
                        if agent_file.exists():
                            agents['cargo'][group_name].append({
                                'id': agent_dir.name,
                                'path': str(agent_dir.relative_to(BASE_DIR))
                            })

    return agents


def update_index():
    """Update AGENT-INDEX.yaml with current agents."""
    agents = scan_agents()

    # Count totals
    total_minds = len(agents['minds'])
    total_cargo = sum(len(v) for v in agents['cargo'].values())
    total_conclave = len(agents['conclave'])
    total = total_minds + total_cargo + total_conclave

    # Generate YAML content
    content = f"""# AGENT-INDEX.yaml
# Auto-generated by agent_index_updater.py
# Last updated: {datetime.now().isoformat()}
# Total agents: {total}

version: "4.1.0"
updated: "{datetime.now().strftime('%Y-%m-%d')}"

totals:
  minds: {total_minds}
  cargo: {total_cargo}
  conclave: {total_conclave}
  total: {total}

# =============================================================================
# MINDS (L3) - Expert Mind Clones
# =============================================================================
minds:
"""
    for agent in agents['minds']:
        content += f"""  - id: {agent['id']}
    path: {agent['path']}/
    has_soul: {str(agent['has_soul']).lower()}
    has_memory: {str(agent['has_memory']).lower()}
    status: active
"""

    content += """
# =============================================================================
# CONCLAVE (L1) - Deliberative Agents
# =============================================================================
conclave:
"""
    for agent in agents['conclave']:
        content += f"""  - id: {agent['id']}
    path: {agent['path']}/
    status: active
"""

    content += """
# =============================================================================
# CARGO (L4) - Functional Roles
# =============================================================================
cargo:
"""
    for group, group_agents in agents['cargo'].items():
        if group_agents:
            content += f"  {group}:\n"
            for agent in group_agents:
                content += f"""    - id: {agent['id']}
      path: {agent['path']}/
      status: active
"""

    # Write file
    AGENT_INDEX.write_text(content)
    return total


def log_update(file_path: str, agent_id: str, layer: str):
    """Log index update."""
    UPDATE_LOG.parent.mkdir(parents=True, exist_ok=True)

    entry = {
        "timestamp": datetime.now().isoformat(),
        "trigger_file": file_path,
        "agent_id": agent_id,
        "layer": layer,
        "action": "index_updated"
    }

    with open(UPDATE_LOG, 'a') as f:
        f.write(json.dumps(entry) + '\n')


def main():
    """Main hook execution."""
    try:
        data = parse_stdin()

        tool_name = data.get('tool_name', '')
        tool_input = data.get('tool_input', {})

        if tool_name not in ['Write', 'Edit']:
            print(json.dumps({"continue": True}))
            return

        file_path = tool_input.get('file_path', '')

        # Check if this is an agent file
        if not is_agent_file(file_path):
            print(json.dumps({"continue": True}))
            return

        # Update the index
        agent_id = extract_agent_id(file_path)
        layer = detect_layer(file_path)
        total = update_index()

        log_update(file_path, agent_id, layer)

        print(json.dumps({
            "continue": True,
            "message": f"📋 AGENT-INDEX.yaml updated ({total} agents)"
        }))

    except Exception as e:
        print(json.dumps({
            "continue": True,
            "warning": f"Agent index update error: {str(e)}"
        }))
        sys.exit(0)


if __name__ == "__main__":
    main()
