#!/usr/bin/env python3
"""
CLAUDE.md Guard Hook - VETO: Blocks CLAUDE.md creation outside sanctioned locations.

Hook Type: PreToolUse (Write|Edit)
Adapted from: aios-core/.claude/hooks/claude_md_guard.py
Date: 2026-02-18

Architecture Rule Enforced:
  CLAUDE.md files are ONLY allowed in these locations:
  - .claude/CLAUDE.md (project instructions)
  - CLAUDE.md (repo root)

  Agent memory MUST use .claude/agent-memory/{slug}/MEMORY.md
  NEVER create CLAUDE.md in code directories, data dirs, or subfolders.

VETO CONDITIONS:
  - Any Write/Edit targeting a CLAUDE.md outside sanctioned paths -> BLOCK
  - Any content containing <claude-mem-context> outside .claude/ -> BLOCK

ERROR HANDLING: fail-CLOSED (2026-02-22 hardening)
  - JSONDecodeError -> BLOCK (can't parse = can't validate)
  - Any Exception -> BLOCK (unknown error = can't validate)
"""

import json
import sys
import os
from pathlib import Path

# Sanctioned CLAUDE.md locations (relative to project root)
SANCTIONED_CLAUDE_MD = {
    "CLAUDE.md",                    # Repo root
    ".claude/CLAUDE.md",            # Project instructions
}

# Patterns that indicate auto-generated memory spam
SPAM_INDICATORS = [
    "<claude-mem-context>",
    "<!-- This section is auto-generated by claude-mem",
    "# Recent Activity",
]


def normalize_path(file_path: str) -> str:
    """Normalize path to relative, forward-slash format."""
    project_dir = os.environ.get('CLAUDE_PROJECT_DIR', '.')

    fp = Path(file_path).resolve()
    pd = Path(project_dir).resolve()

    try:
        rel = fp.relative_to(pd)
        return str(rel).replace("\\", "/")
    except ValueError:
        return file_path.replace("\\", "/")


def is_claude_md(file_path: str) -> bool:
    """Check if the file is a CLAUDE.md file."""
    normalized = file_path.replace("\\", "/")
    return normalized.endswith("/CLAUDE.md") or normalized == "CLAUDE.md"


def is_sanctioned(relative_path: str) -> bool:
    """Check if the CLAUDE.md path is in a sanctioned location."""
    return relative_path in SANCTIONED_CLAUDE_MD


def content_is_spam(content: str) -> bool:
    """Check if content contains auto-generated memory spam markers."""
    if not content:
        return False
    for indicator in SPAM_INDICATORS:
        if indicator in content:
            return True
    return False


def main():
    try:
        input_data = sys.stdin.read()
        if not input_data:
            print(json.dumps({"decision": "allow"}))
            return

        hook_input = json.loads(input_data)
        tool_name = hook_input.get("tool_name", "")
        tool_input = hook_input.get("tool_input", {})

        # Only check Write and Edit tools
        if tool_name not in ("Write", "Edit", "write", "edit"):
            print(json.dumps({"decision": "allow"}))
            return

        file_path = tool_input.get("file_path", "")
        if not file_path:
            print(json.dumps({"decision": "allow"}))
            return

        relative_path = normalize_path(file_path)

        # Check if targeting a CLAUDE.md file
        if not is_claude_md(relative_path):
            print(json.dumps({"decision": "allow"}))
            return

        # Check if it's a sanctioned location
        if is_sanctioned(relative_path):
            content = tool_input.get("content", "")
            if not content:
                content = tool_input.get("new_string", "")

            if content_is_spam(content):
                print(json.dumps({
                    "decision": "allow",
                    "message": (
                        "Warning: CLAUDE.md Guard: Detected claude-mem-context in sanctioned file. "
                        "Agent memory should use .claude/agent-memory/{slug}/MEMORY.md instead."
                    )
                }))
                return

            print(json.dumps({"decision": "allow"}))
            return

        # UNSANCTIONED CLAUDE.md -> BLOCK
        print(json.dumps({
            "decision": "block",
            "reason": (
                f"VETO: CLAUDE.md Guard\n"
                f"   Path: {relative_path}\n"
                f"   Rule: CLAUDE.md files are NOT allowed outside sanctioned locations.\n"
                f"   Sanctioned: {', '.join(sorted(SANCTIONED_CLAUDE_MD))}\n"
                f"   Agent memory -> .claude/agent-memory/{{slug}}/MEMORY.md"
            )
        }))

    except json.JSONDecodeError:
        # Fail-CLOSED: can't parse input = can't validate = BLOCK
        print(json.dumps({
            "decision": "block",
            "reason": "CLAUDE.md Guard: Cannot parse hook input (malformed JSON). Blocking by default."
        }))
    except Exception as e:
        # Fail-CLOSED: unknown error = can't validate = BLOCK
        print(json.dumps({
            "decision": "block",
            "reason": f"CLAUDE.md Guard error (fail-closed): {str(e)}. Blocking by default."
        }))


if __name__ == "__main__":
    main()
